### ISSUE TITLE
MDEV-25670 Run `mysql_upgrade` / `mariadb-upgrade` at startup

### ISSUE THREAD

**Issue by jjlin** [MariaDB/mariadb-docker#350]
I was looking into upgrading my instance of MariaDB from 10.4 to 10.5, and according to https://mariadb.com/kb/en/upgrading-from-mariadb-104-to-mariadb-105/, I'm supposed to run `mysql_upgrade` or `mariadb-upgrade` as part of the upgrade procedure.

I didn't see this being done anywhere in `docker-entrypoint.sh`, so I ran it myself after restarting with the `mariadb:10.5` image. According to the [`mysql_upgrade` docs](https://mariadb.com/kb/en/mysql_upgrade/):

> It's also safe to run `mysql_upgrade` for minor upgrades, as if there are no incompatibles [sic] between versions it changes nothing.

So it seems like it might be a good idea to just always run it as part of startup to make version upgrades more seamless.

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/mysql/issues/130#issuecomment-540947598

**Comment by tianon** [comment]
I'm not totally sure this is -- I think this is somewhere we could use a little guidance from @grooverdan on whether this is something recent versions of MariaDB do automatically like MySQL 8+ has started doing? :innocent: :pray:

**Comment by grooverdan** [comment]
Yep, I agree. Its a good thing to do. Even on minor upgrade there are things it corrects (JSON plugins from 5.7 data directories, mysql.user correctness to name two things I recently remember).

**Comment by tianon** [comment]
I think the most difficult problem is detection of _when_ it ought to be run because it requires the server to be up before it can run (so it requires the same temporary server logic as the initial bootstrapping), so it isn't reasonable to just run it every time (unless MariaDB's version has an offline mode? :innocent:)

**Comment by grooverdan** [comment]
Created https://jira.mariadb.org/browse/MDEV-25670 , might be possible without mysql_upgrade changes.

**Comment by julienfritsch44** [comment]
@timofeyturenko can you please have a look?

**Comment by Thomas131** [comment]
This issue created a downtime for me today (move :latest-tag from 10.5 -> 10.6).

**Comment by grooverdan** [comment]
@Thomas131 can you share your logs of the 10.6 startup. If that' not obvious on the downtime case can you explain it more. Did running mariadb-upgrade/mysql_upgrade in the container resolve it?

**Comment by Thomas131** [comment]
Various websites stated that the error is fixed by mysql_upgrade. My quick fix currently is just pulling the last 10.5.11 and continue running that version - that started without a problem.

10.6.3:
```
2021-07-13 23:25:36+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.3+maria~focal started.
2021-07-13 23:25:37+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-07-13 23:25:37+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.3+maria~focal started.
2021-07-13 23:25:37 0 [Note] mysqld (mysqld 10.6.3-MariaDB-1:10.6.3+maria~focal) starting as process 1 ...
2021-07-13 23:25:37 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-07-13 23:25:37 0 [Note] InnoDB: Number of pools: 1
2021-07-13 23:25:37 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2021-07-13 23:25:37 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2021-07-13 23:25:37 0 [Note] InnoDB: Using Linux native AIO
2021-07-13 23:25:37 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2021-07-13 23:25:37 0 [Note] InnoDB: Completed initialization of buffer pool
2021-07-13 23:25:37 0 [Note] InnoDB: 128 rollback segments are active.
2021-07-13 23:25:37 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-07-13 23:25:37 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-07-13 23:25:37 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-07-13 23:25:37 0 [Note] InnoDB: 10.6.3 started; log sequence number 8589121259; transaction id 20800682
2021-07-13 23:25:37 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-07-13 23:25:37 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2021-07-13 23:25:37 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2021-07-13 23:25:37 0 [Note] Server socket created on IP: '0.0.0.0'.
2021-07-13 23:25:37 0 [Note] Server socket created on IP: '::'.
2021-07-13 23:25:37 0 [Warning] 'proxies_priv' entry '@% root@9fe92f89669c' ignored in --skip-name-resolve mode.
2021-07-13 23:25:37 0 [ERROR] Incorrect definition of table mysql.event: expected column 'definer' at position 3 to have type varchar(, found type char(141).
2021-07-13 23:25:37 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
2021-07-13 23:25:37 0 [Note] mysqld: ready for connections.
Version: '10.6.3-MariaDB-1:10.6.3+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2021-07-13 23:25:37 0 [Note] InnoDB: Buffer pool(s) load completed at 210713 23:25:37
```

**Comment by grooverdan** [comment]
Yes the `mysql.event` error would be fixed by `mysql_upgrade`. Are you using events to the extent that your website's went down on this? A trouble also is that an auto_upgrade with mysql_upgrade would prevent you going back to 10.5.11 so I doubt I can safely enable it as default behaviour.

As you've discovered relying on ":latest" is a little fragile. All suggested improvements welcome.

**Comment by tgruenert** [comment]
Please think about the switch `MARIADB_AUTO_UPGRADE=true|false` mentioned by @ChristianCiach.

I´ve used the bitnami docker where this is implemented without such a switch. As a result a startup with around 300 databases takes 2h - every time and without any things to upgrade. So any release needs a downtime. A total desaster.

On the other side an upgrade might be very usefull if it is really needed.

**Comment by grooverdan** [comment]
@tgruenert thanks for the feedback. I definitely don't want to subject user to this level of pain. If there's some things that could make the entire mariadb-upgrade better esp on 300 database I'm keen to see it in a bug report - https://jira.mariadb.org/ , even if its just what the time is currently spent on (is it in the logs?).

**Comment by tgruenert** [comment]
Hi @grooverdan 
Thank you for your ultra fast response. I tracked down the problem a little. Bug report is https://jira.mariadb.org/browse/MDEV-27060

**Comment by PhrozenByte** [comment]
I agree with @ChristianCiach, not having this in `docker-entrypoint.sh` makes it virtually impossible to do this nicely. A nice approach would be to start a temporary server, run `mariadb-upgrade` and then start the primary server. AFAIK MariaDB won't start the event scheduler after running `mariadb-upgrade`, but requires a server restart, right? So, this is the right approach. We can't even do this ourself by wrapping the default entrypoint, since we can't know whether the temporary or primary server is running, nor whether a server is running at all yet.

Please also note that this is a disadvantage of MariaDB in comparison to MySQL. MySQL is doing auto upgrades since 8.0.16 (https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-16.html).

> A trouble also is that an auto_upgrade with mysql_upgrade would prevent you going back to 10.5.11 so I doubt I can safely enable it as default behaviour.

@grooverdan Since the MariaDB docs specifically tell us to create backups before upgrading, I'd say that this also applies to MariaDB in containers. It means that one must create a backup before pulling new images that might require upgrading (i.e. always for the `10` and `latest` tags and manually when switching to a newer `10.x` tag).

Furthermore, MariaDB isn't supporting downgrades, right? So, by not running `mysql_upgrade` we basically end up in an undefined state in which a rollback is pure luck anyway.

Anyway, a `MARIADB_AUTO_UPGRADE` env variable is a good idea no matter what (like MySQL adding the `--upgrade` server option). I'd strongly vote for enabling it by default, but users should be able to disable it.

**Comment by grooverdan** [comment]
I checked on the event scheduler - since https://github.com/MariaDB/server/commit/18f7dfed1792 `mariadb-upgrade` will enable and it can be manually enabled with `set global event_scheduler=1`:
```
$ sql/mysqld --no-defaults --datadir=/tmp/${PWD##*/}-datadir --socket=/tmp/${PWD##*/}.sock --plugin-dir=${PWD}/mysql-test/var/plugins/ --verbose --skip-networking --event-scheduler=ON
2021-11-18 12:20:07 0 [Note] sql/mysqld (server 10.7.2-MariaDB) starting as process 799749 ...
2021-11-18 12:20:07 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-11-18 12:20:07 0 [Note] InnoDB: Number of transaction pools: 1
2021-11-18 12:20:07 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2021-11-18 12:20:07 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2021-11-18 12:20:07 0 [Note] InnoDB: Completed initialization of buffer pool
2021-11-18 12:20:07 0 [Note] InnoDB: Setting O_DIRECT on file ./ibdata1 failed
2021-11-18 12:20:07 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=70271,70271
2021-11-18 12:20:07 0 [Note] InnoDB: 128 rollback segments are active.
2021-11-18 12:20:07 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2021-11-18 12:20:07 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-11-18 12:20:07 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-11-18 12:20:07 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-11-18 12:20:07 0 [Note] InnoDB: 10.7.2 started; log sequence number 70283; transaction id 94
2021-11-18 12:20:07 0 [Note] InnoDB: Loading buffer pool(s) from /tmp/build-mariadb-server-10.7-datadir/ib_buffer_pool
2021-11-18 12:20:07 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-11-18 12:20:07 0 [Note] InnoDB: Buffer pool(s) load completed at 211118 12:20:07
2021-11-18 12:20:07 0 [ERROR] Incorrect definition of table mysql.event: expected column 'definer' at position 3 to have type varchar(, found type char(141).
2021-11-18 12:20:07 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
2021-11-18 12:20:07 0 [Note] sql/mysqld: ready for connections.
Version: '10.7.2-MariaDB'  socket: '/tmp/build-mariadb-server-10.7.sock'  port: 0  Source distribution

..
$ client/mysql_upgrade   --socket=/tmp/${PWD##*/}.sock --user=dan
Phase 1/7: Checking and upgrading mysql database
Processing databases
mysql
mysql.column_stats                                 OK
mysql.columns_priv                                 OK
mysql.db                                           OK
mysql.event                                        OK
mysql.func                                         OK
mysql.global_priv                                  OK
mysql.gtid_slave_pos                               OK
mysql.help_category                                OK
mysql.help_keyword                                 OK
mysql.help_relation                                OK
mysql.help_topic                                   OK
mysql.index_stats                                  OK
mysql.innodb_index_stats                           OK
mysql.innodb_table_stats                           OK
mysql.plugin                                       OK
mysql.proc                                         OK
mysql.procs_priv                                   OK
mysql.proxies_priv                                 OK
mysql.roles_mapping                                OK
mysql.servers                                      OK
mysql.table_stats                                  OK
mysql.tables_priv                                  OK
mysql.time_zone                                    OK
mysql.time_zone_leap_second                        OK
mysql.time_zone_name                               OK
mysql.time_zone_transition                         OK
mysql.time_zone_transition_type                    OK
mysql.transaction_registry                         OK
Phase 2/7: Installing used storage engines... Skipped
Phase 3/7: Fixing views
mysql.user                                         OK
Phase 4/7: Running 'mysql_fix_privilege_tables'
Phase 5/7: Fixing table and database names
Phase 6/7: Checking and upgrading tables
Processing databases
information_schema
performance_schema
sys
sys.sys_config                                     OK
test
test.table_a                                       OK
Phase 7/7: Running 'FLUSH PRIVILEGES'
OK
$ mc -e 'select @@event_scheduler'
+-------------------+
| @@event_scheduler |
+-------------------+
| ON                |
+-------------------+
```

So no restart is required.

Apart from a `docker exec {container} mariadb-upgrade` after the container its started, I agree, is very hard to wrap the entry point in a sane way.

There's a section on downgrades in:
https://monty-says.blogspot.com/2020/04/upgrading-between-major-mariadb-versions.html

So for a start:

1. `MARIADB_AUTO_UPGRADE=OFF` as a default (might change later if stable)
1. Implement the `mariadb-upgrade` running on the final instance as an option
1. If there's a demand, make it a pre-start option (with upgrade-system-tables only?)
1. on backups https://mariadb.com/kb/en/upgrading-between-major-mariadb-versions/#requirements-for-doing-an-upgrade-between-major-versions - is backing up the `mysql` database to a different database on major upgrade. Sounds like not too much of a burden on the datadir.

I'll get some concepts written for testing.

**Comment by grooverdan** [comment]
As per above link, I've started a proof of concept.
`MARIADB_AUTO_UPGRADE=early` aspects and probably the backup aren't correct yes (can't start the mysqld as root at this point). If its ok by you watchers here, when I add a healthcheck script there will be a `--mariadb-upgrade` argument there that will return success once its upgraded and with this, the `MARIADB_AUTO_UPGRADE=early` aspects of the entry point aren't needed.

Comments/questions/suggested test cases/scenarios welcome.

**Comment by PhrozenByte** [comment]
Thank you @grooverdan :rocket: :+1: I've had two comments about the code, see there. 

According to Monty's blog post it's MariaDB's goal to be backwards compatible. This somewhat means that any later MariaDB major should be able to use the data files of any older MariaDB (and MySQL) major. However, as noted by Monty, this obviously has some limitations, as it would mean that MariaDB could never remove deprecated features otherwise. So, in the end we must think about what `mariadb-upgrade` actually does - and I don't have an answer to this, all what follows now are questions, no statements! Is `mariadb-upgrade` a required step, or rather optional? "Optional" means that by using `mariadb-upgrade`, one can enable new features, but if one chooses not to use those features, it isn't really required to run `mariadb-upgrade`. The question is, at which point does it break? It's kinda silly to think that MariaDB 10.6 could run with a `data` directory from MySQL 1.0 without `mariadb-upgrade`... Thus `mariadb-upgrade` can't be optional, it might be "postponable", but not optional. And, to make things worse, why did MySQL choose to remove `mysql_upgrade` and implement an auto-upgrade feature instead, if `mysql_upgrade` wasn't really required before? What made them require it?

Besides, I was thinking about "early" and "non-early" upgrades. "Early" upgrades have the advantage of running in a clean environment that isn't affected by outside connections, while "non-early" upgrades have the advantage of not delaying the service availability. But, is this actually true? Taking the event scheduler as an example it seems like that running `mariadb-upgrade` in a clean environment isn't really necessary, as it is able to and will enable new features at runtime anyway (this needs checking whether this is true for all features!). Otherwise, @tgruenert mentioned that startup takes 2 hours for him because of `mariadb-upgrade`, so, does this mean that while `mariadb-upgrade` is running, the service isn't available anyway? Also we must take into consideration whether `mariadb-upgrade` is actually expected to run while the service is up normally. The upgrade docs don't really tell. Usually adding something to an upgrade instruction means that one can't use the service for production until all steps are completed, but I'm not so sure about MariaDB and `mariadb-upgrade` anymore. I don't think that it's feasible to support both "early" and "non-early" upgrades. I believe that there must be a "right" answer to this. Before your post I assumed that "early upgrades" were the right solution, but after reading Monty's blog post and your findings, I'm no longer sure about this.

**Comment by grooverdan** [comment]
Yes, removal of features in MariaDB is something that very rarely happens. Without looking hard through change notes I doubt I could think of one.

You are on the right track with `mariadb-upgrade` being optional. It probably would run on a MySQL 1.0 datadir, though I've no test cases to prove this. There are a limited number cases of correcting tables or ensuring data is correct (MDEV-26363),

Why did MySQL autoupgrade? I suspect it makes many of the code paths around running on older versions simpler. There's also many user complains about no downgrades in minor versions across certain version boundaries in 8.0+.

Early vs non-early is pretty much right. For event scheduler, it becomes available after `Phase 4/7: Running 'mysql_fix_privilege_tables'` which would be quite quick into the running version. Other features? yes, we'll have to see. Things like oracle packages in `sqlmode=ORACLE` just require the tables. Other things are more subtle. Overall there aren't that many of them.

On 2 hrs of running mariadb-upgrade, per [MDEV-27060](https://jira.mariadb.org/browse/MDEV-27060?focusedCommentId=206061&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-206061) this can be restricted to system table checks via configuration (and why `early_system_only` was there). The long part here is the `mysqlcheck` and autorepair which is a table by table iteration. There's going to be per table metadata locks here preventing changes of tables which would delay a DDL query, particularly on a large table. For the most part everything looks like it can be completed when the service is up. You're probably right about not being feasible to support both.

So plan:
* Drop early upgrades.
* After this is introduced, add a option healthcheck script (another outstanding feature, can't be on by default because of Docker library policy) with a `--mariadb-upgrade` option which when used, effectively gives the early option.

I thought about adding a `MARIADB_AUTO_UPGRADE=system_only` convenience option, but settable with a configuration option in a configuration file. Anyone with enough tables to want this feature probably already has a configuration file, so I'll just document it.

**Comment by grooverdan** [comment]
Almost final version for review above.

I'm not too fond of having to have a root password around for this, which is hard if `MARIADB_RANDOM_ROOT_PASSWORD` is used. Contemplating 19103e59caab4f047bf65f82745c54c7c574008f as a `mysql@localhost` unix socket auth user that can only be run in the container.

Comments welcome.

**Comment by PhrozenByte** [comment]
I think this is the right way to go. Thank you for the explanations, sounds very reasonable.

I also just checked the code, looks good. Great work! :+1:

I only got one small note: Right now we won't run `mysql_upgrade` when initializing the database. This is right, as it would be a no-op anyway, but it causes the first backup of the `mysql` database to be stored as "unknown version". I'd recommend running `mysql_upgrade` on database init, too. To be more precise: move `docker_mariadb_upgrade` in `_main` below the database init, and move the `[ -z "$DATABASE_ALREADY_EXISTS" ]` check in `docker_mariadb_upgrade` to `docker_mariadb_backup_system`. This way no backup is created on first run, but `mysql_upgrade` is run. `mysql_upgrade` won't do anything besides creating `"$DATADIR"/mysql_upgrade_info`. However, it might reduce confusion when users find a backup of their `mysql` database with an "unknown version".

Additionally, https://github.com/MariaDB/mariadb-docker/commit/19103e59caab4f047bf65f82745c54c7c574008f implements another thing I was doing myself with `docker-entrypoint-initdb.d` until now. Definitely makes things much easier, thank you! :+1: I'd suggest documenting this, too.

Looking forward to the healtcheck script :blush:

**Comment by grooverdan** [comment]
>  I'd recommend running mysql_upgrade on database init, too

I tried this. It caused basic tests to timeout in initialization. Effectively the `mysql_upgrade_info` file just needs to be written with the version and the rest of the `mariadb-upgrade` should be a no-op. I'm going to see how other developers feel about `mysql_install_db` writing this.

**Comment by PhrozenByte** [comment]
> I tried this. It caused basic tests to timeout in initialization.

When being executed *after* database initialization? :confused: Okay. What about running `mysql_upgrade` on the temporary server for database initialization (i.e. as a different code path)?

**Comment by grooverdan** [comment]
It effectively was:
```
diff --git a/docker-entrypoint.sh b/docker-entrypoint.sh
index 9a0043f..2f0fdc3 100755
--- a/docker-entrypoint.sh
+++ b/docker-entrypoint.sh
@@ -329,8 +329,6 @@ docker_setup_db() {
                        docker_process_sql --database=mysql <<<"GRANT ALL ON \`${MARIADB_DATABASE//_/\\_}\`.* TO '$MARIADB_USER'@'%' ;"
                fi
        fi
+       # Put upgrade info on fresh volumes for ease of upgrade determination
+       MYSQL_PWD=$MARIADB_ROOT_PASSWORD mysql_upgrade --socket="${SOCKET}" && chown mysql: "${DATADIR}/mysql_upgrade_info"
 }
```
causing https://github.com/MariaDB/mariadb-docker/runs/4260127024?check_suite_focus=true

Writing the file directly is an option I haven't given up on.

**Comment by PhrozenByte** [comment]
I see. Looks like it isn't a no-op after all, assuming because the file is missing and `mysql_upgrade` doesn't know that it should be a no-op. Yeah, I'd simply write the result of `SELECT VERSION()` to `mysql_upgrade_info` then.

**Comment by grooverdan** [comment]
Small but resolvable differences in verison format.
```
$ podman exec intelligent_herschel mysql -e 'select version()';
version()
10.6.5-MariaDB-1:10.6.5+maria~focal

~/repos/mariadb.org-tools/buildbot.mariadb.org 
$ podman exec intelligent_herschel mysql_upgrade
Phase 1/7: Checking and upgrading mysql database
...
sys.sys_config                                     OK
Phase 7/7: Running 'FLUSH PRIVILEGES'
OK

$ podman exec intelligent_herschel cat /var/lib/mysql/mysql_upgrade_info 
10.6.5-MariaDB
```

https://jira.mariadb.org/browse/MDEV-27068 raised a need to do an early upgrade (of system only). I'm trying to get more details.

**Comment by grooverdan** [comment]
Yes! Implemented! Thanks everyone for your feedback and discussion. It helped significantly. As small changes work their way upstream there is some simplification that should be possible.

**Comment by olafbuitelaar** [comment]
It seems the docker_temp_server_start also tries to start replication, if it's a slave when MARIADB_AUTO_UPGRADE=1 is enabled. 
Maybe it's an idea to start the temp server with; --skip-slave-start ?
as I'm getting these error's during a slave upgrade;
```
[ERROR] Error in Log_event::read_log_event(): 'Event invalid', data_len: 0, event_type: 0
[ERROR] Error reading relay log event: slave SQL thread aborted because of I/O error
[ERROR] Slave SQL: Relay log read failure: Could not parse relay log event entry. The possible reasons are: the master's binary log is corrupted (you can check this by running 'mysqlbinlog' on the binary log), the slave's relay log is corrupted (you can check this by running 'mysqlbinlog' on the relay log), a network problem, or a bug in the master's or slave's MariaDB code. If you want to check the master's binary log or slave's relay log, you will be able to know their names by issuing 'SHOW SLAVE STATUS' on this slave. Internal MariaDB error code: 1594
```
Once upgraded it starts fine, so it would be a minor improvement to the upgrade phase.

**Comment by grooverdan** [comment]
Good idea. ^ added.

Please do a new issue next time. Its easier to keep track of.

**Comment by grooverdan** [comment]
@olafbuitelaar last note for here, if you re-pull the container, it has `--skip-slave-start` there now.

**Comment by olafbuitelaar** [comment]
thanks for the update!
