### ISSUE TITLE
MySQL server has gone away in Windows

### ISSUE THREAD

**Issue by neoacevedo** [MariaDB/mariadb-docker#403]
I have webdevops/php-apache-dev:8.0 and latest mariadb images docker, running in Windows.

My issue: when I run a Laravel or Yii2 migration via console (`docker exec -ti php-container php artisan migrate` for Laravel, `docker exec -ti php-container php yii migrate` for Yii2), I always get in error `MySQL server has gone away`, but it happens only when my docker images are in Windows, but if I run the same docker-compose file in Linux, it runs the commands without any issue.

**Comment by grooverdan** [comment]
Can you show the logs for the mariadb container? If its a crash or similar can you try the container quay.io/mariadb-foundation/mariadb-debug using the same major version tag as your maridab container. Its logs should be a little more verbose.

**Comment by neoacevedo** [comment]
These are the container logs. 

Some what I have noticed is a common error for some tables: `[ERROR] InnoDB: preallocating 163840 bytes for file ./smart/<table>.ibd failed with error (...)` , and when the migration tries to create any index sometimes the process is locked and after a while it continues, another times I get the error `MySQL server has gone away`, where it creates the table but not else any index apart of the primary key.

[log.txt](https://github.com/MariaDB/mariadb-docker/files/7704889/log.txt)
[log (2).txt](https://github.com/MariaDB/mariadb-docker/files/7704888/log.2.txt)

**Comment by neoacevedo** [comment]
Installed ` quay.io/mariadb-foundation/mariadb-debug:10.6` (I'm sorry, only screenshots this time):

![imagen](https://user-images.githubusercontent.com/438372/145845886-6f418307-b37a-4cc5-a3a7-e275fc1336dd.png)
![imagen](https://user-images.githubusercontent.com/438372/145845922-25654d45-d273-4d1c-96e6-67153a9c9f9b.png)
![imagen](https://user-images.githubusercontent.com/438372/145845967-5e485d0d-c558-4b64-a653-77fc2ab333eb.png)
![imagen](https://user-images.githubusercontent.com/438372/145846083-35dcc598-9840-47eb-b684-b51635de50cb.png)
![imagen](https://user-images.githubusercontent.com/438372/145846114-03732297-925b-4ce0-86a1-94fdf98a46ba.png)

**Comment by grooverdan** [comment]
Starting with the error code:
```
$ podman run --rm mariadb:10.6 perror 2
OS error code   2:  No such file or directory

$ errno 2
ENOENT 2 No such file or directory
```

The preallocation that linux uses is `posix_fallocate` which even looking at the manual page:
* take and open file descriptor as an argument
* not documented to return ENOENT

If we look at the first, we see that with an open file descriptor it should already refer to a file, and therefore denying its existance in an error message is quite odd.

Because this is Windows I'm assuming its a WSL version? I'm suspecting something similar to #331 / [MDEV-24189](https://jira.mariadb.org/browse/MDEV-24189), a very clear difference between the linux functions and the WSL implementations.

Like what Vlad did in MDEV-24189 can you instigate a procmon recording of the migration at the same time as recording the strace of the mysqld/mariadbd process.
Process for strace should be something like:
* start mariadb:10.6 container with --cap-add=SYS_PTRACE
* `docker exec {container} sh -c 'apt-get update && apt-get install -y strace`
* `docker exec --user mysql {container} strace -s 99 -p 1 -o /var/lib/mysql/mariadb.strace` (as it crashes the container using a persistent location).
* start procmon
* do migration
* save procmon output, stop procmon
* `docker container cp {container}/var/lib/mysql/mariadb.strace $HOME/mariadb.strace`
* create a [WSL](https://github.com/microsoft/WSL/issues/new?assignees=&labels=&template=Bug_Report.yaml) bug (based on the assumption you are using WSL).

**Comment by grooverdan** [comment]
FYI happy to accept a [Windows](https://github.com/docker-library/official-images#repeatability) based image like [monogo](https://github.com/docker-library/mongo/blob/master/5.0/windows/windowsservercore-ltsc2022/Dockerfile) if anyone has the inclination to port the entrypoint to PowerShell.

**Comment by grooverdan** [comment]
Reported: https://github.com/microsoft/WSL/issues/8443

**Comment by yosifkit** [comment]
> FYI happy to accept a [Windows](https://github.com/docker-library/official-images#repeatability) based image like [monogo](https://github.com/docker-library/mongo/blob/master/5.0/windows/windowsservercore-ltsc2022/Dockerfile) if anyone has the inclination to port the entrypoint to PowerShell.

Note that the windows-based mongo images do not have any entrypoint or initialization logic. Related information in https://github.com/docker-library/postgres/pull/506 and the [official images faq](https://github.com/docker-library/faq/tree/2c48cc77c354ec18edc13ac017a8e2a382fae74c#why-isnt-there-a-windows-equivalent-of-docker-entrypointsh).
