### ISSUE TITLE
Adding a Dockerfile HEALTHCHECK that uses healthcheck.sh

### ISSUE THREAD

**Issue by abernier** [MariaDB/mariadb-docker#419]
Hi,

A `healthcheck.sh` script is [here](https://github.com/MariaDB/mariadb-docker/blob/master/10.8/healthcheck.sh).

What about taking advantage of it inside the `Dockerfile` within a [`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) instruction, something like:

```Dockerfile
HEALTHCHECK CMD /usr/local/bin/healthcheck.sh
```

Thank you

**Comment by grooverdan** [comment]
It wasn't allowed because of https://github.com/docker-library/faq#healthcheck

Thanks for making me dig up the reference, it made me realize that https://github.com/docker-library/healthcheck/blob/master/mysql/Dockerfile.mariadb can be updated.

I'll get one more healthcheck fix 6d048b85e0baa3f5ed7bf37da193eef785ee2098 submitted soon. `--su=mysql` as a work around for now.
