### ISSUE TITLE
Docker sunsets the free Team Organization feature

### ISSUE THREAD

**Issue by christyjacob4** [MariaDB/mariadb-docker#499]
As you're aware, there has been a recent change in Docker's policy around their free Team Organization which will lead to all existing images to be deleted. More info here [https://news.ycombinator.com/item?id=35154025](https://news.ycombinator.com/item?id=35154025)

Since the `mariadb` image is also [hosted on DockerHub](https://hub.docker.com/_/mariadb), I wanted to check how this change will affect it and if we as consumers of the image should be concerned about it in any way or take any necessary steps.

**Comment by grooverdan** [comment]
Saw it.

MariaDB is a Docker Official Image. So its on Docker Hub as Docker's organisation rather than a MariaDB organisation.

This applies to all the [Docker Official Images](https://github.com/docker-library/official-images/tree/master/library).

MariaDB Corporation does have a few images up on their organisation (https://hub.docker.com/r/mariadb/), which they'll be paying for.

The MariaDB Foundation is very happy with its [quay.io service](https://quay.io/organization/mariadb-foundation).
