### ISSUE TITLE
MariaDB 11.1 (preview)

### ISSUE THREAD

**Issue by rentalhost** [MariaDB/mariadb-docker#502]
Are preview versions supported?

**Comment by grooverdan** [comment]
Because we don't do official signed distro packages on the preview releases (like Ubuntu packages) on which the Docker Official Image is made we don't do a Official Docker Image on preview releases either.

However there is a OCI image available on `quay.io/mariadb-foundation/mariadb-devel:11.1-preview` that has the same specification Docker Official Images.

Unsigned packages do exist on `*-autobake` builders on [out CI system for the preview-11.1-preview branch](https://buildbot.mariadb.org/#/grid?branch=preview-11.1-preview) if interested.

**Comment by grooverdan** [comment]
Feedback most welcome, including [bug reports](https://jira.mariadb.org).

**Comment by rentalhost** [comment]
Nice! It worked better than I thought.

On my github workflow, I just set `image`:

```yaml
    services:
      mariadb:
        image: quay.io/mariadb-foundation/mariadb-devel:11.1
```

**Comment by grooverdan** [comment]
If you running a CI system on github for testing, `quay.io/mariadb-foundation/mariadb-devel:X.Y` are kept up to date, along with `quay.io/mariadb-foundation/mariadb-devel:earliest`, `quay.io/mariadb-foundation/mariadb-devel:latest` (as stable version), and `quay.io/mariadb-foundation/mariadb-devel:verylatest` (as beta onwards, so after the alpha preview release). Bug reports on these most welcome too. Its always nicer to get a bug report pre-release :-)
